@startuml Carnet de voyage

package eu.telecomnancy.carnet {

package model {

class Carnet {
  - String title
  - String author
  - LocalDate startDate
  - LocalDate endDate
  - final int days
  - List<String> participants
  - List<DayPage> pages
  + Carnet(String title, String author, LocalDate startDate, LocalDate endDate)
  + fromJSON(JSONObject json)
  + loadFromJSON(String path)
  + addParticipant(String participant)
  + removeParticipant(String participant)
  + setPage(int index, DayPage page)
  + setPage(int index, String title, String description, String photoPath)
  + getPage(int index)
  + getDayDate(int index)
  + toJSON()
  + saveAsJSON(String path)
}

class DayPage {
  - String title
  - String description
  - String photoPath
  + DayPage(String title, String description, String photoPath)
  + DayPage(JSONObject json)
  + toJSON()
}

Carnet "1" *-- "1..*" DayPage

}

class Main {
  ...
}

class MainController {
  ...
}

}

@enduml
